version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: login_mongo
    ports:
      - "27017:27017"
    networks:
      - komfort_net

  login-service:
    build:
      context: ./spring
      dockerfile: Dockerfile
    container_name: login_service
    depends_on:
      - mongo
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/login-db
    networks:
      - komfort_net

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: login_gateway
    depends_on:
      - login-service
    ports:
      - "8080:8080"
    networks:
      - komfort_net

networks:
  komfort_net:
    driver: bridge
