spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: login-register
          uri: http://login-service:8081
          predicates:
            - Path=/api/v1/register
        - id: login-login
          uri: http://login-service:8081
          predicates:
            - Path=/api/v1/login
      default-filters:
        - RemoveResponseHeader=Server

server:
  port: 8080
